### ISSUE TITLE
What's left to do to move the repo to haskell-game

### ISSUE THREAD

**Issue by Mikolaj** [haskell-game/sdl2-ttf#1]
Lets move the discussion from https://github.com/rongcuid/sdl2-ttf/pull/4 to here.

Off the top of my head: 

* give the maintainer (@rongcuid) all kinds of permissions, e.g,. to edit the top repo description line, which should probably say something like "This is the official location of the repo"

* it would be ideal if all the old repo forks (@mankyKitty, @osa1,  @rongcuid) could change their repository description (the one at the top) to something like "The official repo location is now" and then edit the link to point to

    https://github.com/haskell-game/sdl2-ttf

* also, ideally they'd block their issuse interfaces and wikis (I don't think one can block pull requests)

* party!

**Comment by ocharles** [comment]
I have sent @rongcuid an admin invite.

**Comment by rongcuid** [comment]
Accepted

**Comment by mankyKitty** [comment]
I think I still have the package rights on Hackage, should I just take mine
down and let you put yours up or is there a nicer way? :)

**Comment by ocharles** [comment]
I don't think you can remove something from Hackage, so your best option is to give maintainers here upload rights, and we'll have to do a major version bump to clarify the drastically different API (if it is different, I don't actually know anything about this project :smile:)

**Comment by Mikolaj** [comment]
Yes, we bumped the major version, because the API is totally different (but totally equal to the one in sbidin/sdl2-ttf, so a least we are compatible with one of the merged APIs and also, it's been tested before by many users). If users request so, we may also re-add some bits from the original API (but personally, I'd just use Text.pack in user code and keep the API compact and restricted to the fastest bindings at the higher level of the API (not the Raw level)).

@mankyKitty: could you give @rongcuid  and me (a humble sidekick of @rongcuid) upload permissions (it's under `edit package information`)? My nick is https://hackage.haskell.org/user/MikolajKonarski and @rongcuid has https://hackage.haskell.org/user/carldong. Thank you! Also, @sbidin and @ocharles and/or @polarina (or is there a common @haskell-games Hackage user?), would you mind receiving upload permissions in the interest of minimizing the bus factor?

@sbidin: FYI, we are going to upload the merged repo, with your code and your API, to Hackage. Please verify I got the credits, copyrights and licences right (on branch master).

**Comment by sbidin** [comment]
I'm okay with being given upload permissions. As for the credits, copyrights and licences, everything looks good to me. Glad to see this ending up on Hackage! Thanks everyone!

**Comment by ocharles** [comment]
Also happy with being a maintainer.

**Comment by Mikolaj** [comment]
I've just asked hackage devs and they kindly did `sudo apt-get install libsdl2-ttf-dev` so next time we upload the library, the documentation should build automatically (and the build matrix should look fine). :)

Edit: actually, I'm no longer sure about hackage doc-builder, but at least https://matrix.hackage.haskell.org/package/sdl2-ttf is green again.

**Comment by mankyKitty** [comment]
I have added more names to the maintainers list, let me know if anything is
amiss.

:)

**Comment by Mikolaj** [comment]
@rongcuid: I'm thinking, after you publish new version on hackage (I will monitor and upload docs if they don't auto-generate), perhaps it makes sense to leave your old repo https://github.com/rongcuid/sdl2-ttf as is, with the old API, for the people that haven't completed migration to the new API. However, it may make sense to add "This repo is now located at", as in https://github.com/mankyKitty/sdl2-ttf and disable issues and wiki. What do you think?

**Comment by Mikolaj** [comment]
@rongcuid: would now be a good time for a new release? I tested that it works with the official GHC 8.2.1. If you are busy, feel free to delegate the release to me. Cheers!

**Comment by rongcuid** [comment]
I plan on transferring this project to someone else, as I have basically switched to Qt 5 (might not in Haskell) for anything I attempt, and letting someone who is actually using this package to take the Hackage package or something like that. I am not sure about the procedure of doing so, though

**Comment by Mikolaj** [comment]
I guess, the procedure is just that you ask someone. :) E.g., if you decide to ask me, I won't refuse the honour.

**Comment by rongcuid** [comment]
If you wish, you can take over it

**Comment by Mikolaj** [comment]
@rongcuid: thank you. Also, I'm grateful for all the work you expended and all the time you kept maintaining the bindings despite not using them yourself, e.g., when you responded to my requests when I was still a humble user. I'm indebted to you. Good luck with Qt. :)

Does anybody else use the bindings a lot and would like to maintain them instead of me? Let me know. If not, I will mercilessly nag sdl maintainers (@haskell-game) to release new version of sdl and then I will release sdl-ttf to Hackage as well.

**Comment by elben** [comment]
@Mikolaj are you waiting for a post-2.3.0 version of sdl2 before releasing sdl2-ttf 2.0.0? I'm looking forward to using this package—otherwise I'll just reference the git repo in my stack.yml for now.

**Comment by Mikolaj** [comment]
@elben: hi! I think I will release it tomorrow. Will ping you here. :)

**Comment by Mikolaj** [comment]
@elben: released. Happy hacking! :)
