### ISSUE TITLE
sdl2-ttf causes breakage in a working program

### ISSUE THREAD

**Issue by cronokirby** [haskell-game/sdl2-ttf#13]
(on windows 7 64 bit)
The following program works and briefly displays a window
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Lib
    ( someFunc
    )
where

import qualified SDL
import qualified SDL.Font

someFunc :: IO ()
someFunc = do
    SDL.initialize [SDL.InitVideo]
    window <- SDL.createWindow "App" SDL.defaultWindow
    SDL.showWindow window
    SDL.delay 1000
    SDL.destroyWindow window
    SDL.quit
```

Adding 

```haskell
SDL.Font.initialize
```
underneath `SDL.initialize` causes the program to compile and run but no longer show a window. No error message is shown in the output of the program.

I encountered this using stack with the following declared dependencies: 
```
  build-depends:
      base >=4.7 && <5
    , sdl2
    , sdl2-ttf
```

I installed the sdl2 libraries using stack's bundled mysys.

**Comment by Mikolaj** [comment]
Instead of `SDL.initialize [SDL.InitVideo]` (which is probably correct, but I want to match my config) could you try:

```
SDL.initialize [SDL.InitEvents]
SDL.logSetAllPriority $ toEnum 1
SDL.Font.initialize
SDL.initialize [SDL.InitVideo]
```

and share the log?

**Comment by cronokirby** [comment]
When I do that, with `logSetAllPriority` from SDL.Raw.Basic, I get no output whatsoever, like before...

**Comment by Mikolaj** [comment]
Yes, it's `SDL.Raw.Basic`. And what if you remove `SDL.Font.initialize`? Do you get any output then? I get

```
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
```

but that may be because I use renderers. not `showWindow`. But I doubt sdl2-ttf requires renderers. Another thing to try is to load a font file, even some made-up path for a start and you should then get an error about the path:

https://github.com/LambdaHack/LambdaHack/blob/v0.8.3.0/Game/LambdaHack/Client/UI/Frontend/Sdl.hs#L94

Anyway, the project I linked to does compile and work on Windows (Vista at least, last tested with the v0.8.3.0 tag), so you may use it to test your configuration, but beware, the compilation takes a lot of time.

**Comment by cronokirby** [comment]
I think I'm not getting any output at all because of https://github.com/haskell-game/sdl2/issues/86
Will try and build this project.

**Comment by Mikolaj** [comment]
BTW, here's how I build it on the appveyor Windows CI: https://github.com/LambdaHack/LambdaHack/blob/v0.8.3.0/appveyor.yml

**Comment by Mikolaj** [comment]
You can also try without compiling using the CI binaries (I haven't tested them since v0.8.3.0, but people probably occasionally do): https://ci.appveyor.com/project/Mikolaj/allure/build/artifacts

But this doesn't test your toolchain, but only your OS.

**Comment by cronokirby** [comment]
When I try an do some nonsense `font <- SDL.Font.load "foo" 3` still get the same result with the program immediately closing after doing nothing. It seems to me like there's some problem in linking SD2_ttf. But I installed the SDL2 stuff on stack's mysys via
```
stack exec -- pacman -S mingw64/mingw-w64-x86_64-pkg-config mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-SDL2_ttf mingw64/mingw-w64-x86_64-SDL2_image mingw64/mingw-w64-x86_64-SDL2_mixer mingw64/mingw-w64-x86_64-libmikmod```

**Comment by Mikolaj** [comment]
That's very similar to what I do in the appveyor script (but directly with pacman).

On Linux, I'd try to get a backtrace, either with `gdb` or preferably with a profiling build created with ghc using `--enable-profiling --profiling-detail=all-functions` cabal options.

**Comment by cronokirby** [comment]
So I can get a profile log with +RTS -p normally, but as soon as I call any function from SDL.Font
I get nothing at all, nothing gets generated...
something fishy going on here

**Comment by Mikolaj** [comment]
Oh, really strange. Normally you should get a backtrace. If you don't get one, RTS must crash, e.g., in a FFI call to sdl2-ttf. To be sure you are getting good backtraces without sdl2-ttf, you can try inserting `error "foo"` first before and then after `SDL.Font.initialize`. If you get backtrace only the first time, definitely an RTS crash.

**Comment by Mikolaj** [comment]
BTW, which version of the Haskell packages for sdl2 and sdl2-ttf are you using?

**Comment by cronokirby** [comment]
lts 12.10 for stack, which gives me 2.2.4.1.0 for sdl2, and 2.1.0 for sdl2-ttf

**Comment by cronokirby** [comment]
As you predicted, I get a backtrace when I put an error before the first use of SDL.Font, but if SDL.Font.initialize runs before the error, I get nothing at all

**Comment by Mikolaj** [comment]
OK, so you have the most updated versions. I have no clue how to debug a crash on Windows, how to check what shared libraries are used, etc. You can take the binary archive (not the installer) of Allure and replace the sdl .dll files with those found on your system and see if Allure still works (the dlls are probably the same versions). Let me know if you google something helpful or resolve it somehow.

**Comment by Mikolaj** [comment]
Hi @cronokirby. Any news on that one?

**Comment by cronokirby** [comment]
Unfortunately I no longer use windows so...

**Comment by Mikolaj** [comment]
Lucky you. :) If so, let me close the issue. Cheers!
