### ISSUE TITLE
Failed to load interface for ‘SDL.Internal.Exception’

### ISSUE THREAD

**Issue by maiermic** [haskell-game/sdl2-ttf#8]
I tried to build master (https://github.com/haskell-game/sdl2-ttf/commit/d98b475813e5d58aa0408ccf4f8cf4ea114db982) by running `stack install` but I get

```
path/to/haskell-game/sdl2-ttf/src/SDL/Font.hs:104:1: error:
    Failed to load interface for ‘SDL.Internal.Exception’
```

**Comment by ocharles** [comment]
Can you provide some more information? Perhaps steps to reproduce and a full log?

**Comment by maiermic** [comment]
The module `SDL.Internal.Exception` only exists since *sdl2-2.2* but `build-depends` of *sdl2-ttf.cabal* requires `sdl2 >= 2.0`. I can build it if I change it to `sdl2 >= 2.2` and update the resolver in *stack.yaml* to `resolver: lts-8.12`.

**Comment by Mikolaj** [comment]
@maiermic: thank you for the report and the solution, as well, actually: https://github.com/haskell-game/sdl2-ttf/pull/10
